language: C
services:
- docker
script:
- ls
- echo ${TRY}
- echo "script running"
- echo ${db}
- echo ${S01}
env:
  global:
    secure: AUNia1dFrIrJqgWziM8uwv4DAQwuHtKXCSbxyYKrzB2axSb+49TCHdUjhd8/K0sehn/91EASAplj4rEBmsaQv1rcFYpwgxjBUus4d595Y0oGk5rITTO8CeUwPtYFXXS2rMVhgzQQoLmx5tNks7bOtmydjfGEHcMETwVNyTu28wVc9WZ7bPl96SE5y/CFh5Y0aQ+XUZNTB2CrWVurJb3QYSMu66brYs7bHMR5CqTaLtj3wqbGGzR+UxdeQWhrAqDOzi0pQ8v58ZY1u6LNt5RI8tfr2YIWD5jU+PVaTg8jQBtQfPiS3bw9ujSnmArXuSJ2IDkQH/yz3DX486c9a2z+3rcql/XInYTtFVR3UOyNEEXEOjTfGnJBZRuUv03fVenFj6UcTWNNQhwyaJfP0pPOwMfevuc4fy6euQY+7gjaZJgcV+OBP45ztkhIsce0VIvyMkHxoAjRDpKBdsiS/AnzeJw239r7xGB+7a3qzMITeMxAf3G+TfsTXU0PNoy+WSIJZ1ZJ3nkxDq2+1PeqzzZXGMa6NxmNCSTm+Q+scmZVWQ5pZ8g16/06kSzXB3ycLO1ucZw5jq8f7zytaoGxfBvYXk+h3s54tAkBan8JOY7D9bLA2l4IxCkjb1y5E7AOBnvfZg9iYT5zqTj/K1xcFcoL5MbSiaJP4gIiZ97mZaKYm8Y=
