language: C
services:
- docker
script:
- ls
- echo ${TRY}
- echo "script running"
- echo ${db}
- echo ${S01}
env:
  global:
    secure: JdNWVf6PUMrx+eTGWGR8KhHdq5Z/J3p70IAH4bDw5P3rH2X/H77Kzjkg5QVdAHenNhCAg7V72Dku0cw0dZM+E/QcnK7zrgUvqTv//wh/K4aX2eHtUquaIA8Md5puC5HUbmSETSyTkCxharxUr+qaDCSVXO3DL0d7UNe8mGkhvoIn0EeF2rOirsJRhueuQpcJKWW/Ah9kVwXn6Fsvx/OsMdmmVRB8dGvu2keXo+1+CMlUPPA672lAJMfea4v2YKkv0WxPnjhY6yrBkLpChfahvvLvoY81ERrW0mxhMiEIiCLwsHK/8bJLuf8ZYl4r9MdC2ZcZTYayk/ehiXJSpmDEZkIbhgrOSNaeHaaVFGjU55C0lrbiqbyMWE9mxKFmDqA10xIXpr9q5JjFXjy8J04zcfXzHN5xWPz5e8/w5I/jhWXmAYlOMSzu4a4lxJk603AQ3cDaoXq6h/WL+dsUJKnR9xxYOUGKLnCtRhenPCrHs5nwMN0eWlQh7BwhH2cH7yNyOjvKKMXCCcVXdQ+d3sYbCdqj9kH01Vd+LcDnNB3559wfBcLaY1ZloLn6+F9PdM6oiHiyC1A0OujGkSMxikpDW2b1uzp5CSO/+/D7EPp+q/P435W6YjRctHCx2/kbweqrsE/uxXYlCpQzkio4u7FEfZiiPnV7andTYcpPpJ8vVfA=
