language: C
services:
- docker
script:
- ls
- echo ${mytoken}
- echo "script running"
- echo ${db}
env:
  global:
  - secure: h1+R4fxgjTqUjyQGhwYAGvkko2EWJIb8yD99lakiIDeuPpng+kIeG3Ajs1MS9T7yEIZjp22PtRhCc48Fg4QUJ7K7dL9Z6g+QkwTwHL9CCgWt29rwEoFJqmKsItwO2XFUs/hOcQRXJoLQ2Z1+3Raj4ewNQFdH3cW9y/Oep8Pw4Rii3NTSQRN1blAfa+taLp0xlTXs5D81v7iPewKPKA/YKPehHVMRcNMSPFv9uOlmIZHvhjh2Z7lw77om+JbD1lPayVRsAWh5gQjAHQ1p42Qg/PSX919uvsL6b437s8xEulrtYk/T6gAb2uyjgEVPQbPZ6f9bn6luaC2EYAzjV7sR0uP5xf7AaIXmwmt+r5e3M3aewcFG6cU5ucyU91yJiS11LggIKpLKiYuPllrdApYQFpdiAe1ntg/lJ6MCw/XlMctcJ28mIHJv5MIHuMtsuq2ZyexoVc6sSoDb8fTN+dCCJQk4BPSzaeeuJg9xQ5aoGW9uj/KDOdgAOoLjxsLRLUB92ZBsdGpmoDiqVJd7Wrsw3xGUP5Gc8YE4J1vfzdt3yvi2wnhXRizquk1my5X9VdrIGiDSHzN5o3cgUrkjxwh/AcjyHTTIJ41VfYxf7HKbw2Bx+ery7gMQL4i3yUhvDmcLM/0yW1yMvnPvV7V9PhXQ0GIsd26vA3YbH6pmlgNnl9c=
  - secure: jJapUJ5yrMU22QGw7NK6eONVp9WSLdWMSMjphEgyzaglNEsTxxXjNMLw/gCRO+5+y7j5ux2mIt3MTEphbTZF/MvYvROSNx2mxdFsxebVZd6XiefWMNgnY2R4jn1N4DvGoE8s1y8j+YUUbFY8t33O6hh7JuC7qwZ6l9Cp4nj6Qa91KZYyEWQ5DGassOlRnJImQUA1URo8pagafr+hX3yh2hq++1dr7Cn37AsboCMS1+MHL6Z/ErafxELbhd265yfE9sRnZ2qj91owx3spc/cQerH0agewL//Gtce7EGHODYfOVJT1B2pyId65TctPbcI28ZSpH1eLC7LZT8EncasHes8BcbV9k9eCmK1JH+3eXSAs0vJB0Ind5WnMMTxXCZJ+W2+xsmF6aB0aG1foLUGCGKKb0JuTFAIPd4fMjTuzu12pcuCWB25h6euVbNo2mJLIEAb0m7XNM1tGMPDQhEGyh3JViJ5kbh3A6lQP64PjZbvcCbW9f0pBGlMUWJB5aiZscS4V8UtbfoAGFVXBANlop/VXJFQ+7gPvArvbWH4SAFL2YhDn4hHraA1XxnihLj9LjRRWolSm5U1sO7BFbJhOKpTncBhxyb2wFwvGQP6udY0cswfWb1wXCQIZJ/85QmFbaZnBBvMCXATVjR6KMFH7dckzhyTcwwpagFuC0V95tqk=
  jobs:
  - db="debug"
