language: C
# services:
# - docker
# before_install:
# - TOKEN=$TOKEN make build_docker
script:
- echo "Shaping"
- echo "12h30"
#- make debug
- echo debugging
- git remote -v
- touch test04.txt
- git add test04.txt
- git commit -a -m "upload"
-   git remote add origin-pages https://${TOKEN}@github.com/zhoulaifu/hello_travis_ci.git
- git push --quiet --set-upstream origin-pages gh-pages
#- make shaping
#- make sanitizing
#- make fuzzing
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$TOKEN"
  keep_history: true
  on:
    branch: main
env:
  global:
  - IMAGE=test01
  - MOUNT=/mnt/local
  - secure: keL498Dzey8UpyB1FABDfXFlA/hGwvr4onNxJnOMG8E+O5uMQDMmSvCNG2vDg3BZTja4h/GWFqnRbIFgDUI/qEPQfPF9TFW/9Fqfb0f+Pu8d+g9sJAeckCZWQGyJWOl2a2o67hRYjYrcVRtsKKjI75lJ5bl3sYXFhZmjO6OpLS3LBnXpnqsstApiTILVxyAKwfRV+sQpgSmhDia0Yj8xmtOZivDNEdF3o87g2R4/KacvNFXpTUAkO5mnNnea082jlC3ewwmafk6UHYoj7YzcbSBtIHwDCt4SaOTuwTWeoyVE50ek+X5b+r1SULk/nQHkBb9PfD/AenHsFeooK3G8VCLHX8LMjuWK4kadSgKWVF9NZzFzVame5G8ie/oh4F1bJzeNM7XcDjaC+mpe14Gytg9AOh5IrNv/Zp1TL46pK8nAuLNhCj9C/1b6MgNSXilwuZDK0j4whqvjhYoUtzghkiW2SBTdnY0mOSioz50li6FMQirNUeLQYqWfK0VFy5y61FAOq+fVp+EbWlfx7tjXrWU1ZVKAN/Z40RLRYRiuo32K5XIGfo97BNmIurkEMhQ3uk2UUqSzjUDP8szJjFc3kTY9LzlyBcMgAL9rfpisG0kUYLAPtoYf/piVjm6XfBaE3ZS3+hmZH1RIlO6FU1Meg42aSfbXyjThu0UeZEI8+dU=
