language: C
services:
- docker
before_install:
- echo "BEFORE-INSTALL"
- echo ${mytoken}
- docker build  -t "test01" .
script:
- ls
- make

env:
  global:
    secure: h1+R4fxgjTqUjyQGhwYAGvkko2EWJIb8yD99lakiIDeuPpng+kIeG3Ajs1MS9T7yEIZjp22PtRhCc48Fg4QUJ7K7dL9Z6g+QkwTwHL9CCgWt29rwEoFJqmKsItwO2XFUs/hOcQRXJoLQ2Z1+3Raj4ewNQFdH3cW9y/Oep8Pw4Rii3NTSQRN1blAfa+taLp0xlTXs5D81v7iPewKPKA/YKPehHVMRcNMSPFv9uOlmIZHvhjh2Z7lw77om+JbD1lPayVRsAWh5gQjAHQ1p42Qg/PSX919uvsL6b437s8xEulrtYk/T6gAb2uyjgEVPQbPZ6f9bn6luaC2EYAzjV7sR0uP5xf7AaIXmwmt+r5e3M3aewcFG6cU5ucyU91yJiS11LggIKpLKiYuPllrdApYQFpdiAe1ntg/lJ6MCw/XlMctcJ28mIHJv5MIHuMtsuq2ZyexoVc6sSoDb8fTN+dCCJQk4BPSzaeeuJg9xQ5aoGW9uj/KDOdgAOoLjxsLRLUB92ZBsdGpmoDiqVJd7Wrsw3xGUP5Gc8YE4J1vfzdt3yvi2wnhXRizquk1my5X9VdrIGiDSHzN5o3cgUrkjxwh/AcjyHTTIJ41VfYxf7HKbw2Bx+ery7gMQL4i3yUhvDmcLM/0yW1yMvnPvV7V9PhXQ0GIsd26vA3YbH6pmlgNnl9c=
